[package]
name = "antelope-tokens-block-index"
edition = "2021"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams-antelope = "0.6"
substreams = "0.6"
itertools = "^0.13"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
