[package]
name = "antelope-tokens"
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
prost = "0.13"
prost-types = "0.13"
substreams-entity-change = "2"
substreams = { workspace = true }
substreams-antelope = { workspace = true }
antelope = { workspace = true }
