[package]
name = "antelope-tokens"
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.13"
antelope-tokens-events = { path = "../antelope-tokens-events" }
substreams-entity-change = "2"
substreams = { workspace = true }
substreams-antelope = { workspace = true }
antelope = { workspace = true }
