// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub balance_events: ::prost::alloc::vec::Vec<Balance>,
    #[prost(message, repeated, tag="2")]
    pub supply_events: ::prost::alloc::vec::Vec<Supply>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    /// ExtendedSymbol
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    /// Name
    #[prost(string, tag="2")]
    pub owner: ::prost::alloc::string::String,
    /// Asset
    #[prost(string, tag="3")]
    pub balance: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub is_deleted: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Supply {
    /// ExtendedSymbol
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    /// Asset
    #[prost(string, tag="2")]
    pub supply: ::prost::alloc::string::String,
    /// Asset
    #[prost(string, tag="3")]
    pub max_supply: ::prost::alloc::string::String,
    /// Name
    #[prost(string, tag="4")]
    pub issuer: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub is_deleted: bool,
}
// @@protoc_insertion_point(module)
