[package]
name = "block-index"
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams-antelope = { workspace = true }
substreams = { workspace = true }
itertools = "^0.13"
