// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub balance_events: ::prost::alloc::vec::Vec<Balance>,
    #[prost(message, repeated, tag="2")]
    pub supply_events: ::prost::alloc::vec::Vec<Supply>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    /// block
    #[prost(message, optional, tag="1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    /// balance
    ///
    /// ExtendedSymbol
    #[prost(string, tag="4")]
    pub token: ::prost::alloc::string::String,
    /// Name
    #[prost(string, tag="5")]
    pub owner: ::prost::alloc::string::String,
    /// Asset.amount
    #[prost(int64, tag="6")]
    pub balance: i64,
    /// db_op::Operation
    #[prost(string, tag="7")]
    pub operation: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Supply {
    /// block
    #[prost(message, optional, tag="1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(string, tag="3")]
    pub block_hash: ::prost::alloc::string::String,
    /// supply
    ///
    /// ExtendedSymbol
    #[prost(string, tag="4")]
    pub token: ::prost::alloc::string::String,
    /// Asset.amount
    #[prost(int64, tag="5")]
    pub supply: i64,
    /// Asset.amount
    #[prost(int64, tag="6")]
    pub max_supply: i64,
    /// Name
    #[prost(string, tag="7")]
    pub issuer: ::prost::alloc::string::String,
    /// db_op::Operation
    #[prost(string, tag="8")]
    pub operation: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
