[package]
name = "antelope-tokens-events"
edition = { workspace = true }
version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
prost = "0.13"
prost-types = "0.13"
substreams = { workspace = true }
substreams-antelope = { workspace = true }
antelope = { workspace = true }
